### ISSUE TITLE
One packet number space as mandatory to implement?

### ISSUE THREAD

**Issue by mirjak** [mirjak/draft-lmbdhk-quic-multipath#4]
I took the following text from draft-liu:

`Note: Even if use of multiple packet number spaces is negotiated but a peer uses an zero length connection ID, then all packets sent to that peer MUST be numbered in a single number space (as specified in the previous section), because the packet level decryption implementation will only see one Connection ID sequence number (the default number 0).`

This basically makes the one packet number handling mandatory to implement as you also need it if multiple packet number spaces were negotiated but zero length CID is used.

The alternative would be to say that you can't used zero length CID if multiple packet number spaces are negotiated.

Also I'm currently proposing  enable_multipath=1 for multiple number space and enable_multipath=2 for one number space to be compatible with the draft-liu and the alibaba implementation. However if we think one packet number space is mandatory to implement, it would make more sense to have it the other way around and allow fallback to one packet number space, namely if the client ask for two packet number spaces but the server supports only one but would also lead to a successful negotiation.

What do people think about this?

**Comment by mirjak** [comment]
@huitema any views?

**Comment by Yanmei-Liu** [comment]
Agree with Christian's design for value definitions.
Submitted PR #20 for this issue.
