### ISSUE TITLE
Mechanisms to avoid path timeout

### ISSUE THREAD

**Issue by yfmascgy** [mirjak/draft-lmbdhk-quic-multipath#51]
The current draft says that "Servers SHOULD stop sending traffic on paths through where no non-probing packet was received in the last 3 path RTTs". However, it is possible that only a few data was generated in the past few RTTs due to app-limit conditions, and as a result, only one path was used. So I think, in section 3.2.3, we should suggest the use of some keep-alive mechanisms such as sending ping frames on a particular path if one is interested in keeping that path alive. Let me know what you think?

**Comment by Yanmei-Liu** [comment]
Let's get back to the problem Yunfei mentioned, I just submitted PR #74 for it.

By the way, do we need a transport parameter to negotiate max path idle timeout? Like the connection max_idle_timeout in RFC9000, to prevent one of the endpoints end up the path too early...

**Comment by mirjak** [comment]
Why would you have different max_idle_timeout for different paths?

**Comment by yfmascgy** [comment]
> Why would you have different max_idle_timeout for different paths?

The max_idle_timeout defined in RFC9000 is used to close whole connection, but not the path. In order to close an idle path more precisely, one might need sth like max_path_idle_timeout. I think we want all paths to have the same max_path_idle_timeout values, which is used to control when a path should be closed when no non-probing packets was received on that path. Another approach is to use PING frame to keep a path alive.
