### ISSUE TITLE
Handshake negotiation: what does "Allowed server responses" mean

### ISSUE THREAD

**Issue by LPardue** [mirjak/draft-lmbdhk-quic-multipath#75]
In Section 2 you define a transport parameter and set of values. These are presented in a table with a column header "Allowed server responses", what does that mean? One way to read this is that it implies servers would tailor their Transport Parameters to the value sent by the client but that's conflicting with our philosophy that TPs are unilateral declarations, not active negotiation.

So the question for me is, is this just a wording issue or a design one?

**Comment by mirjak** [comment]
I think this mainly means that server are not allow to send 0x3. However, if the client sends 0x3, the server's reply will impact the client behaviour for 1-RTT packets. Is that a negotiation? However, keep in mind that the intention is not to publish this as it.

**Comment by LPardue** [comment]
unilateral negotiation is ok by me. If that's the intent then maybe just rewording of the table to be clariy it is a matrix of combinations is ok, and state somewhere that server 0x3 is illegal.

> keep in mind that the intention is not to publish this as it.

do you mean not to adopt the draft with this type of TP, or the final RFC? I think better clarity is needed for implementation and experiementation as we try and answer the PN question

**Comment by huitema** [comment]
@LPardue that's my fault. I wrote that table based on my implementation, in which the server response does depend on the client proposal. We should replace it by a matrix showing what is expected if the client proposes 0-1-2-3 and the server 0-1-2-3. The only problematic case is "3 and 3", and we should simply state what happens there.

**Comment by huitema** [comment]
@LPardue please review PR #76

**Comment by LPardue** [comment]
@huitema thanks for the clarification, the new text makes the intent much more clear IMO.

**Comment by mirjak** [comment]
Just to clarify, we are not intending to have this in the final *RFC*. We would like to have it adopted as it to enable more experimentation.

**Comment by LPardue** [comment]
thanks @mirjak that also works for me!
