### ISSUE TITLE
[single packet number space] talk about ack delay measurement

### ISSUE THREAD

**Issue by kazuho** [mirjak/draft-lmbdhk-quic-multipath#79]
To estimate path delay accurately, loss recovery of QUIC utilizes the ACK Delay field of ACK frame (see [RFC 9002; section 5.3.2](https://quicwg.org/base-drafts/rfc9002.html#section-5.3-2)).

However, when single packet number space is being used, it is difficult for the sender to obtain ACK Delay for all the paths being used, because ACK Delay is reported only for the packet carrying the largest packet number. It is the only the ACK delay of the path with shortest path-delay that can be reported.

I think it might be a good idea to acknowledge this shortcoming in the documentation, so that we do not miss the downside when we compare the approaches (or when we try to address the shortcomings of the single packet number space approach).

**Comment by yfmascgy** [comment]
I agree that this issue should be addressed in the current draft. Regarding the problem itself, I think using the one-way timestamp can solve this problem for single PN.

**Comment by mirjak** [comment]
I believe this is discuss in section 5: https://mirjak.github.io/draft-lmbdhk-quic-multipath/draft-lmbdhk-quic-multipath.html#name-computing-path-rtt

Can you propose a PR if you think more text is useful?!

**Comment by qdeconinck** [comment]
I think Section 5 should relate to both packet number space designs, while this issue is specific to one. I summarised the discussion in #85.

**Comment by huitema** [comment]
Yes, there is an issue with single space here. Suppose that the sender sends packets 1 and later 3 on path long delay path A, packets 2 and later 4 on short delay path B. The receiver will get the packets in the order 2, 1, 4, 2. The ACK will be:

* ACK, highest = 2. Ack delay = time ACK sent minus time 2 received.
* ACK, highest = 2, also ACK 1. Ack delay = time ACK sent minus time 2 received.
* ACK, highest = 4, also ACK 2 and 1. Ack delay = time ACK sent minus time 4 received.
* ACK, highest = 4, also ACK 3, 2 and 1. Ack delay = time ACK sent minus time 4 received.

The RTT of path B will be evaluated precisely, with the help of the ACK delay. The RTT of path A will be evaluated less precisely. When the ACK of 2 and 1 is received, the sender cannot use the ACK delay to narrow the estimate of the RTT of path A. Same for packet 4.
